FROM alpine:3.20
RUN apk add --no-cache tor \
 && mkdir -p /var/lib/tor/folio \
 && chown -R tor /var/lib/tor \
 && chmod 700 /var/lib/tor /var/lib/tor/folio
COPY torrc /etc/tor/torrc
USER tor
CMD ["tor", "-f", "/etc/tor/torrc"]
